add_newline = false

[character]
success_symbol = "[â¯](bold white)"

[aws]
disabled = true

[package]
display_private = true

# Starship doesn't have any module for showing docker symbol
# Issue: https://github.com/starship/starship/issues/393
[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.{yml,yaml} files"
command = "echo ðŸ³"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """
format = "in [$output]($style) "
